Add database
ZaharovJaroslav/java-filmorate pull request #9
Opened 2024-07-01 05:48 UTC by ZaharovJaroslav

2024-07-02 21:37 UTC, Yang-Pi requested changes

2024-07-02 21:37 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Film film = filmStorage.getFilmById(filmId);
В том случае, если фильм все же есть, то запрос, сделанный на 80й строке, фактически является лишним. 
getFilmById вернет или фильм, или ничего - если ничего, то кидай исключение, если же фильм - продолжай метод.
Нужно оптимально использовать ресурсы подключения к бд, те не делать запросов, которые можно избежать.

2024-07-02 21:37 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/user/UserStorage.java
> +    boolean isContains(int id);
Вот этот метод не очень вписывается в концепцию интерфейса на самом деле

2024-07-04 05:54 UTC, ZaharovJaroslav commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/user/UserStorage.java
> +    boolean isContains(int id);
Не вписывается потому что лишний раз дергает базу?

2024-07-04 10:53 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/user/UserStorage.java
> +    boolean isContains(int id);
Да
Он может быть в рамках класса, реализующего интерфейс, если например, дешевле узнать есть ли объект в базе, чем делать каки-то манипуляции, но не стоит продвигать его через интерфейс

2024-07-04 10:53 UTC, Yang-Pi approved these changes

2024-07-17 08:35 UTC, closed without merging